server:
  port: 8089
  servlet:
    context-path: /

spring:
  application:
    name: college-admin-service

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    com.campsync.college: DEBUG
