server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    banner-mode: "off"

gateway:
  jwt:
    secret: "super_secret_signing_key_for_campxsync_platform_2026"
    issuer: "campxsync"
  services:
    platform: "http://localhost:8088"
    college: "http://localhost:8089"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
